services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tally-ai

    env_file:
      - .env

    depends_on:
      - postgres
      - ollama

    stdin_open: true
    tty: true

  postgres:
    image: postgres:17
    container_name: tally-postgres

    environment:
      POSTGRES_DB: tally_db
      POSTGRES_USER: tally
      POSTGRES_PASSWORD: tally123

    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: tally-ollama

    ports:
      - "11434:11434"

volumes:
  postgres_data:
  ollama_data: